name: Build and Release (Manual)

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name for the release (e.g., v10)'
        required: true
        type: string

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Build and package extension
        run: npm run package
      
      - name: Get version from manifest
        id: get_version
        run: |
          VERSION=$(node -p "require('./extension/manifest.json').version")
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Extension version: $VERSION"
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: chrome-issue-reporter-v${{ steps.get_version.outputs.version }}
          path: chrome-issue-reporter-extension.zip
          retention-days: 90
      
      - name: Create new tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag -a "${{ inputs.tag_name }}" -m "Release ${{ inputs.tag_name }}"
          git push origin "${{ inputs.tag_name }}"
      
      - name: Delete previous releases
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          echo "Deleting previous releases..."
          NEW_TAG="${{ inputs.tag_name }}"
          
          # Get all releases (just tagName field)
          RELEASES=$(gh release list --limit 100 --json tagName || echo '[]')
          
          # Delete all releases except the new one (they will be recreated with only the new one)
          if [ "$RELEASES" != "[]" ]; then
            echo "$RELEASES" | jq -r '.[].tagName' | while IFS= read -r tag; do
              if [ -n "$tag" ] && [ "$tag" != "$NEW_TAG" ]; then
                echo "Deleting release: $tag"
                gh release delete "$tag" --yes || true
              fi
            done
          fi
          
          # Delete all tags except the new one
          git fetch --tags
          git tag -l | while IFS= read -r tag; do
            if [ "$tag" != "$NEW_TAG" ]; then
              echo "Deleting tag: $tag"
              git push --delete origin "$tag" || true
              git tag -d "$tag" || true
            fi
          done
          
          echo "Cleanup complete"
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ inputs.tag_name }}
          name: Release ${{ inputs.tag_name }}
          files: chrome-issue-reporter-extension.zip
          make_latest: true
          body: |
            ## Chrome Issue Reporter ${{ inputs.tag_name }}
            
            ### ⚠️ IMPORTANT: Download the Correct File
            
            **✅ Download:** `chrome-issue-reporter-extension.zip` (the built extension package)
            
            **❌ DO NOT download:** Source code (zip) or Source code (tar.gz) - these contain the repository structure and will NOT work with Chrome!
            
            ### Installation Instructions
            
            1. **Download** `chrome-issue-reporter-extension.zip` from the Assets section below
            2. **Extract** the ZIP file to a permanent location on your computer
            3. **Open Chrome** and navigate to `chrome://extensions/`
            4. **Enable** Developer mode (toggle in the top-right corner)
            5. **Click** "Load unpacked" and select the extracted folder
            
            📖 For detailed step-by-step instructions, see [INSTALL.md](https://github.com/${{ github.repository }}/blob/main/INSTALL.md)
            
            ### What's Included
            
            This package contains:
            - Complete Chrome extension files (Manifest V3)
            - All required JavaScript, HTML, and JSON files
            - Ready to load directly into Chrome
            
            ### Configuration Required
            
            After installation, configure the extension:
            1. Open the extension's **Options** page
            2. Sign in with GitHub
            3. Select your target repository
            4. Start creating issues!
            
            📖 See [QUICKSTART.md](https://github.com/${{ github.repository }}/blob/main/QUICKSTART.md) for a 7-minute setup guide
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
